language: node_js
node_js:
  - "node"

after_script:
  - npm i
  - grunt
  - cd dist 
  - git init
  - git config user.name "liuxinxin0043"
  - git config user.email "2861706215@qq.com"
  - git add .
  - git commit -m "baidu login"
  - git push --force --quiet "https://${ACC_TOKEN}@${GH_REF}" master:${BRANCH}

branches:
  only:
    - master